name: Release GeRuDok Builds
run-name: Preparing release number ${{ github.run_number }} for GeRuDok
on:
  push:
    tags:
      - '**'
permissions:
  contents: write
jobs:
  build-app:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
          java-package: 'jdk'
          architecture: 'x64'
      - name: Generate file list
        shell: pwsh
        run: (Get-ChildItem -Filter "*.java" -Recurse $pwd | Select FullName | ft -hidetableheaders | Out-String).Trim() | Out-File -FilePath sources.txt
      - name: Create folder for .class files
        shell: pwsh
        run: mkdir bin
      - name: Build .class files
        shell: pwsh
        run: javac "@sources.txt" -d bin
      - name: Build jar
        shell: pwsh
        run: jar cfe "app\GeRuDok.jar" mehanickoPrebacivanje.Main -C bin .
      - name: Generate runtime
        shell: pwsh
        run: jlink --add-modules java.base,java.desktop --strip-debug --no-man-pages --no-header-files --compress=2 --output jre
      - name: Generate application
        shell: pwsh
        run: jpackage --type app-image --input app\ --name "GeRuDok" --main-jar "GeRuDok.jar" --runtime-image jre --dest package\
      - name: Zip application
        shell: pwsh
        run: Compress-Archive package\GeRuDok GeRuDok.zip
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: GeRuDok.zip
